spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ksur
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  application:
    name: SHOPPING-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
